baseURL = 'https://nafees.digital/'
languageCode = 'en-us'
title = "Nafees Hassan"
theme = 'PaperMod'

paginate = 5
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
pygmentsUseClasses = true

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Nafees Hassan"
description = "Nafees Hassan's Site"
keywords = [ "Blog", "Portfolio", "Nafees", "Programming" ]
DateFormat = "2 January, 2006"
author = "Nafees"

ShowShareButtons = true
ShowReadingTime = true
ShowToc = true
ShowBreadCrumbs = false
ShowCodeCopyButtons = true

	[params.assets]
	favicon = "/favicon.ico"
	favicon16x16 = "/favicon.ico"
	favicon32x32 = "/favicon.ico"
	apple_touch_icon = "/favicon.ico"
	safari_pinned_tab = "/favicon.ico"

	[params.label]
	text = "Nafees Hassan"

	[params.homeInfoParams]
	Title = "Nafees Hassan"
	Content = """
Computer Programmer, Open Source enthusiast,
with a interest in low level and efficient computing
"""

	[[params.socialIcons]]
	name = "github"
	url = "https://github.com/Nafees10"

	[params.cover]
	hidden = true
	hiddenInList = true
	hiddenInSingle = true

	[params.editPost]
	URL = "https://github.com/Nafees10/nafees10.github.io/tree/master/content"
	Text = "Suggest Changes"
	appendFilePath = true

	[params.fuseOpts]
	isCaseSensitive = false
	shouldSort = true
	location = 0
	distance = 1_000
	threshold = 0.4
	minMatchCharLength = 0
	keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "About"
name = "About"
url = "/about"
weight = 10

[[menu.main]]
identifier = "Projects"
name = "Projects"
url = "/projects"
weight = 20

[[menu.main]]
identifier = "Blog"
name = "Blog"
url = "/posts"
weight = 30

[[menu.main]]
identifier = "Archive"
name = "Archive"
url = "/archive"
weight = 40

[markup.highlight]
noClasses = false
